### ISSUE TITLE
2.4のデプロイコマンド実行で、先に進めません。。。

### ISSUE THREAD

**Issue by kazukiochiai** [memememomo/serverless-spa-sample-v2#1]
[2.4デプロイコマンドを実行]を進めています。
いくつかのエラーが出ているようなのですが、理由がわからないので、ご教示いただけないでしょうか。

#### 1.脆弱性チェック
依存モジュールをインストール時に、脆弱性チェックに引っかかっているようなのですが、
無視してよいものでしょうか？
　　フロントエンド　：　2 vulnerabilities (1 high, 1 critical)
　　プロジェクト　　：　10 vulnerabilities (3 moderate, 2 high, 5 critical)

#### 2.ServerlessStackのデプロイコマンドを実行
以下のように、失敗します。何が原因かご確認いただけないでしょうか。

```
D:********\serverless-spa-sample-v2>AWS_PROFILE=sst npx sst deploy
'AWS_PROFILE' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。

D:********\serverless-spa-sample-v2>npx sst deploy
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Using stage: dev
Preparing your SST app
Detected tsconfig.json
Transpiling source
Linting source
Running type checker
Building Lambda function src/list.main
Building Lambda function src/create.main
Building Lambda function src/get.main
Building Lambda function src/update.main
Building Lambda function src/delete.main
Building Next.js site frontend
warn  - Invalid next.config.js options detected:
  - The root value has an unexpected property, target, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).

See more info here: https://nextjs.org/docs/messages/invalid-next-config
warn  - The `target` config is deprecated and will be removed in a future version.
See more info here https://nextjs.org/docs/messages/deprecated-target-config
info  - Linting and checking validity of types...

./src/error.ts
4:34  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Creating an optimized production build...
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
Failed to compile.

D:********\serverless-spa-sample-v2\frontend\node_modules\next\dist\build\webpack\loaders\next-client-pages-loader.js?absolutePagePath=private-next-pages%2F_app.tsx&page=%2F_app!
Module not found: Can't resolve 'private-next-pages/_app.tsx' in '\\192.168.11.33\BackUp\D********\serverless-spa-sample-v2\frontend'

D:********\serverless-spa-sample-v2\frontend\node_modules\next\dist\build\webpack\loaders\next-client-pages-loader.js?absolutePagePath=private-next-pages%2Findex.tsx&page=%2F!
Module not found: Can't resolve 'private-next-pages/index.tsx' in '\\192.168.11.33\BackUp\D********\serverless-spa-sample-v2\frontend'

D:********\serverless-spa-sample-v2\frontend\node_modules\next\dist\build\webpack\loaders\next-client-pages-loader.js?absolutePagePath=private-next-pages%2Flogin%2Findex.tsx&page=%2Flogin!
Module not found: Can't resolve 'private-next-pages/login/index.tsx' in '\\192.168.11.33\BackUp\D********\serverless-spa-sample-v2\frontend'

D:********\serverless-spa-sample-v2\frontend\node_modules\next\dist\build\webpack\loaders\next-client-pages-loader.js?absolutePagePath=private-next-pages%2Fnotes%2F%5Bid%5D%2Fedit.tsx&page=%2Fnotes%2F%5Bid%5D%2Fedit!
Module not found: Can't resolve 'private-next-pages/notes/[id]/edit.tsx' in '\\192.168.11.33\BackUp\D********\serverless-spa-sample-v2\frontend'

D:********\serverless-spa-sample-v2\frontend\node_modules\next\dist\build\webpack\loaders\next-client-pages-loader.js?absolutePagePath=private-next-pages%2Fnotes%2F%5Bid%5D%2Findex.tsx&page=%2Fnotes%2F%5Bid%5D!
Module not found: Can't resolve 'private-next-pages/notes/[id]/index.tsx' in '\\192.168.11.33\BackUp\D********\serverless-spa-sample-v2\frontend'


> webpack config.resolve.alias was incorrectly overridden. https://nextjs.org/docs/messages/invalid-resolve-alias

Error: There was a problem building the "Site" NextjsSite.
    at NextjsSite.buildApp (D:********\serverless-spa-sample-v2\node_modules\@serverless-stack\resources\src\NextjsSite.ts:588:13)
    at new NextjsSite (D:********\serverless-spa-sample-v2\node_modules\@serverless-stack\resources\src\NextjsSite.ts:146:16)
    at new MyStack (D:********\serverless-spa-sample-v2\stacks\MyStack.ts:63:18)
    at Object.main (D:********\serverless-spa-sample-v2\stacks\index.ts:10:3)
    at Object.<anonymous> (D:********\serverless-spa-sample-v2\.build\run.js:93:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)

There was an error synthesizing your app.
```

**Comment by memememomo** [comment]
@kazukiochiai 
お問い合わせいただきまして、ありがとうございます。

> 1.脆弱性チェック

デプロイ自体には影響はありませんので、いったん無視しても問題ありません。
もし、このサンプルプログラムをもとにアプリを作成して一般公開する場合は、セキュリティ的に問題がありますので、対処することをおすすめします。
本件は、使用しているモジュールに脆弱性が見つかっている状態です。以下のコマンドで対象のモジュールを確認することができます。

`npm audit`

対象のモジュールをバージョンアップすることで、問題を解決することができます。
バージョンアップすると、サンプルプログラムが動作しなくなり、修正する必要が出てくる可能性がありますので、まずデプロイしてみたい場合は、バージョンアップを一旦保留にすることをおすすめします。


> 2.ServerlessStackのデプロイコマンドを実行

エラーメッセージから推察するとWindows上でコマンドを実行されていると思いますが、実行環境はMac前提となっております。


> D:********\serverless-spa-sample-v2>AWS_PROFILE=sst npx sst deploy
> 'AWS_PROFILE' は、内部コマンドまたは外部コマンド、
> 操作可能なプログラムまたはバッチ ファイルとして認識されていません。

こちらのコマンドはMac上で実行することを前提としていますので、Windows上では不正なコマンドとして認識されてしまっているようです。
コマンドの内容としては、

- AWS_PROFILEという環境変数に sst という文字列を設定
- npx sst deployコマンドを実行

ですので、Windowsで同様の設定いただければ、正常に動作するかもしれません。


以上です。
ご確認よろしくお願いいたします。

**Comment by kazukiochiai** [comment]
ご回答ありがとうございます。
1点目の脆弱性の件は、承知しました。
2点目は、MAC前提だったのですね・・・おっしゃる通り、Windows環境で実施しております。
前半の環境変数部分を別途実施して、npx sst deployコマンドを実施しても、同様の事象となっています。
・・・どうしたものか。。。悩みます。。。

**Comment by kazukiochiai** [comment]
解消しました。
2点目の方は、ネットワークフォルダをマウントして実行していたのですが、
これをローカルドライブのフォルダに変更したら、先に進めました。
当方固有の環境による問題でした。すいません・・・
